name: External Content Sync

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      POSTGRES_URL: ${{ secrets.EXTERNAL_SYNC_POSTGRES_URL }}
      JWT_SECRET: ${{ secrets.EXTERNAL_SYNC_JWT_SECRET }}
      APP_ENV: production
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Download modules
        working-directory: backend
        run: go mod download

      - name: Run external sync
        run: make external-sync
